version: '3.1'

services:
  frontend:
    build:
      context: .
    restart: always
    volumes:
      - app:/app
    environment:
      VUE_APP_URL_BACKEND: http://backend:3000
    ports:
      - '3001:80'
    networks:
      - apps

volumes:
  app:

networks:
  apps:
    external:
      name: apps
