version: '3.1'

services:
  frontend:
    build:
      context: .
    restart: always
    volumes:
      - app:/app
    ports:
      - '3001:80'
    networks:
      - apps

volumes:
  app:

networks:
  apps:
    external:
      name: apps
